resources:
- statefulset.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: sqlserver-env
  literals:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Coding@1234?
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=sqlserver

secretGenerator:
- name: sqlserver-secrets
  envs:
  - .sqlserver.secrets
