apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplaceservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketplaceservice
  template:
    metadata:
      labels:
        app: marketplaceservice
    spec:
      containers:
        - name: marketplaceservice
          image: oussamahdidou/marketplaceserviceapi:latest
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASS
              value: guest
            - name: DB_HOST
              value: sqlserver
---
apiVersion: v1
kind: Service
metadata:
  name: marketplaceservice
spec:
  selector:
    app: marketplaceservice
  ports:
    - port: 80
      targetPort: 8080
